# Basic
title: 知末的博客
# subtitle: 技术为主的博客，偶尔放松写点其他
# welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: 欲将心事付瑶琴。知音少，弦断有谁听。
# creator: <a href="http://onev.cat">@onevcat</a>

# url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
# cover_color: blue

# The blog button should not be removed.
blog_button:
    title: Blog
    description: 技术为主，娱乐为辅

# Navigation buttons in the front page.
# nav:
#    - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: xyzhimo
    # duoshuo:

# Social
social:
    #weibo: xyzhimo
    github: xyzhimo
    twitter: xyzhimo
    gplus: 105644845392959402904
    youtube: xyzhimo
    mail: zhimo.xiao@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
