# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://mazhuang.org
date_format: "ordinal"
title: 知末的博客
subtitle: "欲将心事付瑶琴。知音少，弦断有谁听。"
description: "欲将心事付瑶琴。知音少，弦断有谁听。"
keywords: 知末, zhimo, xyzhimo
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: zhimo xiao
organization: songxiaocai.com
organization_url: http://www.songxiaocai.com
github_username: xyzhimo
location: Hangzhou, China
email: zhimo.xiao@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

#  -
#   href: /about/
#    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: xyzhimo/xyzhimo.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!!  请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: xyzhimo
    repo: blog-comments
    oauth:
        client_id: 3e6a5dbc89d96d203758
        client_secret: a04051de7608c9cebb89add9d1496db32e09e798
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: xyzhimo
    repo: blog-comments
    clientID: 3e6a5dbc89d96d203758
    clientSecret: a04051de7608c9cebb89add9d1496db32e09e798
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
